# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-memory-mcp" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "e0bea4ddef9e5b7b354dfca2782f5074addad2dacea72763e79e8073b26582a3"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "115c9b67b60f8a7812a6fbceca24acb4dabaf981e3bc1eb707ba08ac0a9d7b08"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b703bb9cbbc8359384da605bd297162fa1f6a2c7109b236105f26a406fdb7f5"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "a5a4c050a583d01155d3580a3846e7b09f651c578c94259ebcbd14c194586522"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-arm64.tar.gz"
    end
  end

  name "agent-memory-mcp"
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-memory-mcp"

  # No zap stanza required

end
