# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-memory-mcp" do
  version "0.6.2"

  on_macos do
    on_intel do
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-amd64.tar.gz"
      sha256 "786b4ca99c09d6ca28cf9961b0abb9ed7846307dc9167a15ffbbaa30e2008d09"
    end
    on_arm do
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-arm64.tar.gz"
      sha256 "c8b6bef54e0fdd8e6a8185d639cd841abcacd73f4b36d2a172866d380bb62b88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-amd64.tar.gz"
      sha256 "5a9212046fd008fda26e2d4badca980cb4767ae7adb2abf3f628d84ddbdaaccb"
    end
    on_arm do
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-arm64.tar.gz"
      sha256 "85267c026604efdfe6201e5db225259edbdb9193d3b89a47761397f690cb7160"
    end
  end

  name "agent-memory-mcp"
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-memory-mcp"

  # No zap stanza required

end
