# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-memory-mcp" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "871e3b8d6546dc6d05c826e9e5cea9cffe5e224342efec6d5fbb0cf5be62152e"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "6c4cc045f56744edd154189b5544b1a9f8b4c9aa96b66be452cddb7504584fc6"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c98d52c936f8d4e4fe8cee203358fc133e0a31d07290999a3134d912379212e"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "bb9da185e8b195049acb6ec2ec1d36fb72988cb8ff1cc61f1687aa34ecbc384b"
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v#{version}/agent-memory-mcp-#{version}-linux-arm64.tar.gz"
    end
  end

  name "agent-memory-mcp"
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-memory-mcp"

  # No zap stanza required

end
