# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentMemoryMcp < Formula
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.1/agent-memory-mcp-0.5.1-darwin-amd64.tar.gz"
      sha256 "000275464f0f4c5c361e32ceab1c99fd81160edaed5d31ba50ced940b52291b5"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.1/agent-memory-mcp-0.5.1-darwin-arm64.tar.gz"
      sha256 "7a3bf5f82510d391b5a8483d1d441b88bae390e36f362dfe5d820ea5e785f1ce"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.1/agent-memory-mcp-0.5.1-linux-amd64.tar.gz"
      sha256 "563a5b2bf6f6f76f7ae090f72085db93aec74b5980f7b59a431fe5f3c048001a"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.1/agent-memory-mcp-0.5.1-linux-arm64.tar.gz"
      sha256 "8a8c56a418746a4319f6178ba7507451ffd4102c7926df950873165124fd2bbf"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  def post_install
    (etc/"agent-memory-mcp").mkpath
    config_file = etc/"agent-memory-mcp/config.env"
    unless config_file.exist?
      config_file.write <<~EOS
        # agent-memory-mcp service configuration
        # Edit this file and the service will auto-reload within ~30 seconds.
        # Or send SIGHUP: kill -HUP $(pgrep agent-memory-mcp)

        # HTTP daemon mode (required for brew services)
        MCP_HTTP_MODE=http
        MCP_HTTP_HOST=127.0.0.1
        MCP_HTTP_PORT=18080

        # Data storage
        MCP_DATA_PATH=#{var}/agent-memory-mcp
        MCP_MEMORY_DB_PATH=#{var}/agent-memory-mcp/memory-store/memories.db
        MCP_RAG_INDEX_PATH=#{var}/agent-memory-mcp/rag-index
        MCP_LOG_PATH=#{var}/log/agent-memory-mcp/mcp-diagnostics.log

        # Memory (enabled by default)
        MCP_MEMORY_ENABLED=true

        # RAG document search (disabled by default — enable after setting MCP_ROOT)
        MCP_RAG_ENABLED=false
        # MCP_ROOT=/path/to/your/project
        # MCP_INDEX_DIRS=docs,README.md,CHANGELOG.md

        # Embeddings
        MCP_EMBEDDING_MODE=auto
        OLLAMA_BASE_URL=http://localhost:11434
        # JINA_API_KEY=
        # OPENAI_API_KEY=
      EOS
    end
    (var/"agent-memory-mcp/memory-store").mkpath
    (var/"agent-memory-mcp/rag-index").mkpath
    (var/"log/agent-memory-mcp").mkpath
    system bin/"agent-memory-mcp", "setup"
  end

  def caveats
    <<~EOS
      agent-memory-mcp is installed and Claude Code hooks are configured.

      To start the background service:
        brew services start agent-memory-mcp

      What's automatic:
        - SessionEnd: captures session knowledge
        - PreCompact: saves checkpoint before context compression
        - SessionStart: loads context + compiles pending summaries

      Config: #{etc}/agent-memory-mcp/config.env
      Hooks:  ~/.claude/settings.json
      Data:   #{var}/agent-memory-mcp/
      Logs:   #{var}/log/agent-memory-mcp/

      To reconfigure hooks: agent-memory-mcp setup
      To enable RAG: set MCP_RAG_ENABLED=true in config.env
    EOS
  end

  service do
    run [opt_bin/"agent-memory-mcp", "serve", "--config", etc/"agent-memory-mcp/config.env"]
    keep_alive true
    log_path var/"log/agent-memory-mcp/service.log"
    error_log_path var/"log/agent-memory-mcp/service.err.log"
    working_dir var/"agent-memory-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-memory-mcp 2>&1", 1)
  end
end
