# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentMemoryMcp < Formula
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.8.0/agent-memory-mcp-0.8.0-darwin-amd64.tar.gz"
      sha256 "7d2f4f5cc9e01ab5ce15e700b0c15b775d2f68afebd047bd6ffb277de7117ab5"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.8.0/agent-memory-mcp-0.8.0-darwin-arm64.tar.gz"
      sha256 "7ae81e6403d591d00782c9a491740f5910a00da0eb2320b2e23bfb2ece8e94de"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.8.0/agent-memory-mcp-0.8.0-linux-amd64.tar.gz"
      sha256 "47939d872a6cb4acdab32c679d3b4670ae7ec83565b10b3f58889ae92d625911"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.8.0/agent-memory-mcp-0.8.0-linux-arm64.tar.gz"
      sha256 "4a21f3cc6544152220f1295c0d685599fbe6b8e16b547d7d77aa25db78740ae7"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  def post_install
    (etc/"agent-memory-mcp").mkpath
    config_file = etc/"agent-memory-mcp/config.env"
    unless config_file.exist?
      config_file.write <<~EOS
        # agent-memory-mcp service configuration
        # Edit this file and the service will auto-reload within ~30 seconds.
        # Or send SIGHUP: kill -HUP $(pgrep agent-memory-mcp)

        # HTTP daemon mode (required for brew services)
        MCP_HTTP_MODE=http
        MCP_HTTP_HOST=127.0.0.1
        MCP_HTTP_PORT=18080

        # Data storage
        MCP_DATA_PATH=#{var}/agent-memory-mcp
        MCP_MEMORY_DB_PATH=#{var}/agent-memory-mcp/memory-store/memories.db
        MCP_RAG_INDEX_PATH=#{var}/agent-memory-mcp/rag-index
        MCP_LOG_PATH=#{var}/log/agent-memory-mcp/mcp-diagnostics.log

        # Memory (enabled by default)
        MCP_MEMORY_ENABLED=true

        # RAG document search (disabled by default — enable after setting MCP_ROOT)
        MCP_RAG_ENABLED=false
        # MCP_ROOT=/path/to/your/project
        # MCP_INDEX_DIRS=docs,README.md,CHANGELOG.md

        # Embeddings
        MCP_EMBEDDING_MODE=auto
        OLLAMA_BASE_URL=http://localhost:11434
        # JINA_API_KEY=
        # OPENAI_API_KEY=
      EOS
    end
    (var/"agent-memory-mcp/memory-store").mkpath
    (var/"agent-memory-mcp/rag-index").mkpath
    (var/"log/agent-memory-mcp").mkpath
  end

  def caveats
    <<~EOS
      Run once to configure Claude Code auto-capture:
        agent-memory-mcp setup

      To start the background service:
        brew services start agent-memory-mcp

      Config: #{etc}/agent-memory-mcp/config.env
      Data:   #{var}/agent-memory-mcp/
      Logs:   #{var}/log/agent-memory-mcp/
    EOS
  end

  service do
    run [opt_bin/"agent-memory-mcp", "serve", "--config", etc/"agent-memory-mcp/config.env"]
    keep_alive true
    log_path var/"log/agent-memory-mcp/service.log"
    error_log_path var/"log/agent-memory-mcp/service.err.log"
    working_dir var/"agent-memory-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-memory-mcp 2>&1", 1)
  end
end
