# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentMemoryMcp < Formula
  desc "MCP server with persistent agent memory and RAG semantic search"
  homepage "https://github.com/ipiton/agent-memory-mcp"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.0/agent-memory-mcp-0.5.0-darwin-amd64.tar.gz"
      sha256 "2180e0f44600c3c5e116b44a67e934b5f358e753d811b44eec4e75276805f393"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.0/agent-memory-mcp-0.5.0-darwin-arm64.tar.gz"
      sha256 "06f217689dbe364e0bbc979b3ceb5e4314bccd034e0bdadc6da04d92d826c8b9"

      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.0/agent-memory-mcp-0.5.0-linux-amd64.tar.gz"
      sha256 "35b3332fb151b7e4f4c75b6b8d154835068ffb10dc7f1c41c92be9bdd90a2990"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipiton/agent-memory-mcp/releases/download/v0.5.0/agent-memory-mcp-0.5.0-linux-arm64.tar.gz"
      sha256 "f92afddc60dd9f78a6f041dabf41bded619a6b2051c7997ca92cc7e18c196437"
      define_method(:install) do
        bin.install "agent-memory-mcp"
      end
    end
  end

  def post_install
    (etc/"agent-memory-mcp").mkpath
    config_file = etc/"agent-memory-mcp/config.env"
    unless config_file.exist?
      config_file.write <<~EOS
        # agent-memory-mcp service configuration
        # Edit this file and the service will auto-reload within ~30 seconds.
        # Or send SIGHUP: kill -HUP $(pgrep agent-memory-mcp)

        # HTTP daemon mode (required for brew services)
        MCP_HTTP_MODE=http
        MCP_HTTP_HOST=127.0.0.1
        MCP_HTTP_PORT=18080

        # Data storage
        MCP_DATA_PATH=#{var}/agent-memory-mcp
        MCP_MEMORY_DB_PATH=#{var}/agent-memory-mcp/memory-store/memories.db
        MCP_RAG_INDEX_PATH=#{var}/agent-memory-mcp/rag-index
        MCP_LOG_PATH=#{var}/log/agent-memory-mcp/mcp-diagnostics.log

        # Memory (enabled by default)
        MCP_MEMORY_ENABLED=true

        # RAG document search (disabled by default — enable after setting MCP_ROOT)
        MCP_RAG_ENABLED=false
        # MCP_ROOT=/path/to/your/project
        # MCP_INDEX_DIRS=docs,README.md,CHANGELOG.md

        # Embeddings
        MCP_EMBEDDING_MODE=auto
        OLLAMA_BASE_URL=http://localhost:11434
        # JINA_API_KEY=
        # OPENAI_API_KEY=
      EOS
    end
    (var/"agent-memory-mcp/memory-store").mkpath
    (var/"agent-memory-mcp/rag-index").mkpath
    (var/"log/agent-memory-mcp").mkpath
  end

  def caveats
    <<~EOS
      agent-memory-mcp is ready to run as a background service.

      To start:
        brew services start agent-memory-mcp

      Config: #{etc}/agent-memory-mcp/config.env
      Logs:   #{var}/log/agent-memory-mcp/
      Data:   #{var}/agent-memory-mcp/

      To enable RAG document search, edit config.env and set:
        MCP_RAG_ENABLED=true
        MCP_ROOT=/path/to/your/project
        MCP_INDEX_DIRS=docs,README.md
      Changes are picked up automatically within ~30 seconds.
    EOS
  end

  service do
    run [opt_bin/"agent-memory-mcp", "serve", "--config", etc/"agent-memory-mcp/config.env"]
    keep_alive true
    log_path var/"log/agent-memory-mcp/service.log"
    error_log_path var/"log/agent-memory-mcp/service.err.log"
    working_dir var/"agent-memory-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-memory-mcp 2>&1", 1)
  end
end
